services:
  web:
    build:
      context: .
    image: unclesema2/bd-lab-1-8:latest
    pull_policy: build
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
